### PR TITLE
Bug Fixes/Performance Improvements Bundle

### LINKED ISSUE #8: Incorrect data
I tried to read https://github.com/davidanthoff/StatFiles.jl/blob/master/test/types.sas7bdat, and I essentially get incorrect data for every single field :) You can see the expected values [here](https://github.com/davidanthoff/StatFiles.jl/blob/master/test/runtests.jl#L14).

### PR DESCRIPTION
**Pull request by tk3369**
Bugs fixes #8, #14, and #15.
Performance improvement for parsing numerical values (related to #10)

### CODE REVIEW

**Comment by xiaodaigh** [comment]
On a 4 core 8 thread machine, my propriety product's (read + write to csv speed) is about 25x faster than SASLib's single-threaded pure read speed. Assuming SASLib achieves multithreading which yields a 3.5x speed up the (r+w) performance will still outperform SASLib's pure read by ~7x.

So plenty of optimization possible left on the table! Hope to see a Julia implementation as fast as Rust's

**Comment by tk3369** [comment]
Hi @xiaodaigh, it's good to hear about your test results.  I have never thought the bar can be set so high ;-)  Is your product converting from SAS7BDAT to CSV?  Can you tell me some characteristics about your test scenario - how many rows and columns and what data types & sizes are for each column?

This PR focuses on numerical parsing speed.  I'm just about to push another change that should further improve by an order of 30% or so.

I have not done any work on string columns.  That's probably something to tackle next before I would consider throwing in multithreading.

**Comment by xiaodaigh** [comment]
what os are you using i will try to send you a binary so you can test?

**Comment by tk3369** [comment]
> what os are you using i will try to send you a binary so you can test?

I use Macbook Pro as a primary dev platform.  I also have access to a Linux server for more stressful tests.

```
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

```

**Comment by xiaodaigh** [comment]
Windows by any chance? if not i will compile it on my mac and share.

**Comment by tk3369** [comment]
Sorry, not a big fan of Windows...

**Comment by xiaodaigh** [comment]
@tk3369 How do I share it with you? Can't find your email. If you can can you send me and email at d followed by zj (three letters total) at my company which is analytixware dot com.

**Pull request merged**
